import { Cairo, Montserrat, Bebas_Neue } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import AllProviders from "./AllProvider";
import NavAction from "@/Components/Navbar/NavAction";
import Footer from "@/Components/footer/Footre";

const cairo = Cairo({
  subsets: ["arabic", "latin"],
  weight: ["200", "400", "700", "1000"],
  variable: "--font-cairo",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "400", "900"],
  variable: "--font-montserrat",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
          precedence="default"
        />
      </head>
      <body className={`${cairo.variable} ${montserrat.variable} `}>
        <AllProviders>
          <NavAction />
          <main className="min-h-[calc(100vh-100px)]">
            {children}
            <SpeedInsights />
          </main>
          <Footer />
        </AllProviders>
      </body>
    </html>
  );
}
